[project]
name = "llm-from-scratch-gpt2"
version = "0.1.0"
description = "GPT-2 from scratch"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.3",
    "tensorflow>=2.20.0",
    "tiktoken>=0.11.0",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
