[project]
name = "llm-from-scratch-gpt2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.3",
    "tiktoken>=0.11.0",
    "torch>=2.8.0",
]
